# hindi_alerts.py

hindi_alerts = {
    "200m": "आप 200 मीटर के संकेत की ओर बढ़ रहे हैं।",
    "50-100m": "सावधान! 50 से 100 मीटर के आगे।",
    "Ahead-Left": "आगे बाएं मोड़ के लिए तैयार रहें।",
    "Ahead-Right": "आगे दाएं मोड़ के लिए तैयार रहें।",
    "Axle-load-limit": "एक्सल लोड सीमा आगे।",
    "Barrier Ahead": "आगे बैरियर है।",
    "Bullock Cart Prohibited": "बैलगाड़ी प्रतिष्ठित है।",
    "Cart Prohobited": "कार्ट प्रतिष्ठित हैं।",
    "Cattle": "मार्ग पर गाय हैं। सावधानी से चलें।",
    "Compulsory Ahead": "आपको सीधे आगे जाना है।",
    "Compulsory Keep Left": "बाएं रखें। यह अनिवार्य है।",
    "Compulsory Left Turn": "आपको बाएं मुड़ना आवश्यक है।",
    "Compulsory Right Turn": "आपको दाएं मुड़ना आवश्यक है।",
    "Cross Road": "एक क्रॉसरोड आ रहा है।",
    "Cycle Crossing": "क्रॉसिंग पर साइकिलिस्टों के लिए सावधान रहें।",
    "Compulsory Cycle Track": "आपको साइकिल ट्रैक का उपयोग करना है।",
    "Cycle Prohibited": "इस जगह पर साइकिल निषिद्ध है।",
    "Dangerous Dip": "सावधानी! खतरनाक डिप आगे है।",
    "Falling Rocks": "गिरते पत्थरों से सावधान रहें।",
    "Ferry": "एक फेरी क्रॉसिंग है।",
    "Gap in median": "आगे मीडियन में एक अंतर है।",
    "Give way": "अन्य वाहनों को रास्ता दें।",
    "Hand cart prohibited": "हैंडकार्ट प्रतिष्ठित हैं।",
    "Height limit": "ऊचाई सीमा आगे है। अपने वाहन की ऊचाई जाँचें।",
    "Horn prohibited": "इस क्षेत्र में हॉर्न नहीं बजाने की अनुमति नहीं है।",
    "Humpy Road": "सावधानी! ऊँची रास्ते पर है।",
    "Left hair pin bend": "बाएं हेयर पिन मोड़ के लिए तैयार रहें।",
    "Left hand curve": "आगे बाएं हाथ की मोड़ है।",
    "Left Reverse Bend": "बाएं पलटी हुई मोड़ के लिए तैयार रहें।",
    "Left turn prohibited": "बाएं मुड़ना प्रतिष्ठित है।",
    "Length limit": "लंबाई सीमा आगे है। अपने वाहन की लंबाई जाँचें।",
    "Load limit 5T": "अधिकतम भार सीमा 5 टन है।",
    "Loose Gravel": "सावधानी! रास्ते पर छूटे हुए बालू हैं।",
    "Major road ahead": "आगे मुख्य सड़क है।",
    "Men at work": "सावधान रहें, सड़क पर काम कर रहे लोग हैं।",
    "Motor vehicles prohibited": "मोटर वाहन प्रतिष्ठित हैं।",
    "Nrrow bridge": "आगे संकीर्ण पुल है।",
    "Narrow road ahead": "आगे संकीर्ण सड़क है।",
    "Straight prohibited": "इस क्षेत्र में सीधा चलना नहीं है।",
    "No parking": "इस जगह पर पार्किंग प्रतिष्ठित है।",
    "No stoping": "रुकना निषेध है।",
    "One way sign": "यह एक-तरफा सड़क है।",
    "Overtaking prohibited": "इस जगह पर ओवरटेकिंग नहीं है।",
    "Pedestrian crossing": "क्रॉसिंग में पैदल चलने वालों के लिए सावधान रहें।",
    "Pedestrian prohibited": "पैदल चलने प्रतिष्ठित हैं।",
    "Restriction ends sign": "पिछली प्रतिबंध समाप्त हो गई है।",
    "Right hair pin bend": "दाएं हेयर पिन मोड़ के लिए तैयार रहें।",
    "Right hand curve": "आगे दाएं हाथ की मोड़ है।",
    "Right Reverse Bend": "दाएं पलटी हुई मोड़ के लिए तैयार रहें।",
    "Right turn prohibited": "दाएं मुड़ना प्रतिष्ठित है।",
    "Road wideness ahead": "आगे रास्ता चौड़ा हो रहा है।",
    "Roundabout": "एक राउंडआउट के पास जा रहे हैं।",
    "School ahead": "सावधान रहें, आगामी में स्कूल है।",
    "Side road left": "बाईं ओर साइड रोड की अपेक्षा करें।",
    "Side road right": "दाईं ओर साइड रोड की अपेक्षा करें।",
    "Slippery road": "सावधानी! रास्ता चिकना है।",
    "Compulsory sound horn": "हॉर्न अनिवार्य है।",
    "Speed limit": "गति सीमा लागू है।",
    "Staggred intersection": "स्टैगर्ड इंटरसेक्शन के लिए तैयार रहें।",
    "Steep ascent": "सावधानी! ऊंचाई में चढ़ाई है।",
    "Steep descent": "सावधानी! ऊंचाई में गिरावट है।",
    "Stop": "रुकें! पूर्ण रुकावट आवश्यक है।",
    "Tonga prohibited": "टोंगा प्रतिष्ठित है।",
    "Truck prohibited": "ट्रक प्रतिष्ठित हैं।",
    "Compulsory turn left ahead": "आपको आगे बाएं मुड़ना है।",
    "Compulsory right turn ahead": "आपको आगे दाएं मुड़ना है।",
    "T-intersection": "टी-इंटरसेक्शन के लिए तैयार रहें।",
    "U-turn prohibited": "यू-टर्न प्रतिष्ठित है।",
    "Vehicle prohibited in both directions": "दोनों दिशाओं में वाहन प्रतिष्ठित हैं।",
    "Width limit": "चौड़ाई सीमा आगे है। अपने वाहन की चौड़ाई जाँचें।",
    "Y-intersection": "वाय-इंटरसेक्शन के लिए तैयार रहें।",
    "Sign_C": "सी-साइन आगे है।",
    "Sign_T": "टी-साइन आगे है।",
    "Sign_S": "एस-साइन आगे है।",
    "No entry": "प्रवेश नहीं है! आगे बढ़ें नहीं।",
    "Compulsory Keep Right": "दाएं रखें। यह अनिवार्य है।",
    "Parking": "आप यहां पार्क कर सकते हैं।"
}

