# marathi_alerts.py

marathi_alerts = {
    "200m": "तुम्हाला 200 मीटर चिन्हाच्या कडे आहात.",
    "50-100m": "सावधान! 50 ते 100 मीटर आघाडी.",
    "Ahead-Left": "आघाडीस डावे मोडीस तयार राहा.",
    "Ahead-Right": "आघाडीस उजवे मोडीस तयार राहा.",
    "Axle-load-limit": "एक्झल लोड सीमा आघाड.",
    "Barrier Ahead": "आघाडीस एक बॅरियर आहे.",
    "Bullock Cart Prohibited": "गायबाच्या गाड्या निषेध.",
    "Cart Prohobited": "कार्ट्स निषेध.",
    "Cattle": "मार्गावर गाई आहे. सावधानीस चालवा.",
    "Compulsory Ahead": "तुम्हाला सर्वोत्तम आगे जावं लागतं.",
    "Compulsory Keep Left": "डावे ठेवा. हे आपल्यास बाध्यकृत आहे.",
    "Compulsory Left Turn": "तुम्हाला डावीकडे मोडणे आवश्यक आहे.",
    "Compulsory Right Turn": "तुम्हाला उजवीकडे मोडणे आवश्यक आहे.",
    "Cross Road": "एक सडकचे क्रॉसरोड आहे.",
    "Cycle Crossing": "क्रॉसिंगमध्ये सायकलिस्टं सावधानीस चालवा.",
    "Compulsory Cycle Track": "तुम्हाला सायकल ट्रॅक वापरणे आवश्यक आहे.",
    "Cycle Prohibited": "इथे सायकल निषेध आहे.",
    "Dangerous Dip": "सावधान! खतरनाक डिप आघाड.",
    "Falling Rocks": "खतरनाक शिळें. सावधानीस चालवा.",
    "Ferry": "एक फेरी क्रॉसिंग आहे.",
    "Gap in median": "आघाडीस मीडियनमध्ये एक अंतर आहे.",
    "Give way": "इतर वाहनांना दार द्या.",
    "Hand cart prohibited": "हँडकार्ट निषेध.",
    "Height limit": "उंची सीमा आघाड. आपल्या वाहनाची उंची तपासा.",
    "Horn prohibited": "या क्षेत्रात हॉर्न नका बजवा.",
    "Humpy Road": "सावधान! हंपी रोड आघाड.",
    "Left hair pin bend": "डावा हेअर पिन मोडीस तयार राहा.",
    "Left hand curve": "आघाडीस डाव्या हाताने मोड होणार आहे.",
    "Left Reverse Bend": "डावा पुनरावर्तन मोडीस तयार राहा.",
    "Left turn prohibited": "डावीकडे मोडणे निषेध.",
    "Length limit": "लांबी सीमा आघाड. आपल्या वाहनाची लांबी तपासा.",
    "Load limit 5T": "मानक लोड सीमा 5 टन्स.",
    "Loose Gravel": "सावधान! मार्गावर फिरकी आहे.",
    "Major road ahead": "आघाडीस म्हणजेच मुख्य सडक आहे.",
    "Men at work": "सावधान रहा, मार्गावर काम करत आहे.",
    "Motor vehicles prohibited": "मोटर वाहने निषेध.",
    "Nrrow bridge": "संकीर्ण पुल आघाडी.",
    "Narrow road ahead": "आघाडीस मार्ग संकीर्ण होतंय.",
    "Straight prohibited": "कोणत्याही प्रकारचे चालन येथे निषेध.",
    "No parking": "इथे पार्किंग निषेध आहे.",
    "No stoping": "कुठलेही थांबवू नका.",
    "One way sign": "हे एकच मार्ग आहे.",
    "Overtaking prohibited": "ओव्हरटेकिंग येथे नका.",
    "Pedestrian crossing": "क्रॉसिंगमध्ये पैदल चालकांसाठी सावधानीस चालवा.",
    "Pedestrian prohibited": "पैदल निषेध.",
    "Restriction ends sign": "मागील प्रतिबंध समाप्त झाले आहे.",
    "Right hair pin bend": "उजवा हेअर पिन मोडीस तयार राहा.",
    "Right hand curve": "आघाडीस उजव्या हाताने मोड होणार आहे.",
    "Right Reverse Bend": "उजवा पुनरावर्तन मोडीस तयार राहा.",
    "Right turn prohibited": "उजवीकडे मोडणे निषेध.",
    "Road wideness ahead": "आघाडीस मार्ग सुधारणार आहे.",
    "Roundabout": "एक वर्तुळाकार आघाडी.",
    "School ahead": "सावधान रहा, आगामीत शाळा आहे.",
    "Side road left": "डाव्या किनार्यात एक साइड रोड आहे.",
    "Side road right": "उजव्या किनार्यात एक साइड रोड आहे.",
    "Slippery road": "सावधान! मार्ग स्लिपरी आहे.",
    "Compulsory sound horn": "हॉर्न आवश्यक आहे.",
    "Speed limit": "गती सीमा पालन केली जाते.",
    "Staggred intersection": "स्थानांतर इंटरसेक्शनसाठी तयार राहा.",
    "Steep ascent": "सावधान! उंची वाढ आघाड.",
    "Steep descent": "सावधान! उंची घट आघाड.",
    "Stop": "थांबा! पूर्ण थांबणे आवश्यक आहे.",
    "Tonga prohibited": "टोंगा निषेध.",
    "Truck prohibited": "ट्रक निषेध.",
    "Compulsory turn left ahead": "तुम्हाला डावीकडे मोडणे आवश्यक आहे.",
    "Compulsory right turn ahead": "तुम्हाला उजवीकडे मोडणे आवश्यक आहे.",
    "T-intersection": "एक टी-इंटरसेक्शनसाठी तयार राहा.",
    "U-turn prohibited": "यू-टर्न निषेध.",
    "Vehicle prohibited in both directions": "उभ्या दिशेने वाहनांक निषेध.",
    "Width limit": "अंच मर्ज सीमा आघाड. आपल्या वाहनाची अंच तपासा.",
    "Y-intersection": "एक वाय-इंटरसेक्शनसाठी तयार राहा.",
    "Sign_C": "सी-साईन आघाड.",
    "Sign_T": "टी-साईन आघाड.",
    "Sign_S": "एस-साईन आघाड.",
    "No entry": "प्रवेश नाही! आगवा नका.",
    "Compulsory Keep Right": "उजव्यात ठेवा. हे आपल्यास बाध्यकृत आहे.",
    "Parking": "तुम्ही इथे पार्क करू शकता."
}

